blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("store_article", views.store_article, name="store_article"),
    path("article/<str:slug>/<int:article_id>", views.article, name="article"),
    path("edit_article/<str:slug>/<int:article_id>", views.edit_article, name="edit_article"),
]

website/urls.py
from django.urls import path

from . import views

app_name = "website"

urlpatterns = [
    path("", views.index, name="index"),
    path("projects", views.projects, name="projects"),
]

website/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    github_link = models.URLField(null=True, blank=True)
    preview_link = models.URLField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name

class ProjectImage(models.Model):
    project = models.ForeignKey(Project,
                                related_name='images',
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to="uploads/images/articles")
    is_main = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.project.title

website/views.py
from django.shortcuts import render

from blog.models import Article

from .models import Project


def index(request):
    template_name = "website/index.html"
    articles = Article.objects.filter()
    if not request.user.is_staff:
        articles = articles.filter(published=True)

    context = {
        "articles": articles,
    }
    return render(request, template_name, context)


def projects(request):
    template_name = "website/projects.html"
    projects = Project.objects.filter()

    context = {
        "projects": projects,
    }
    return render(request, template_name, context)

website/templates/website/base_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="theme-color" content="#1c1b24" />
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dodzi Raynard | Website</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <link rel="stylesheet" href="{% static 'css/website_style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/website_style_res.css' %}" />
  </head>
  <body>
    <div id="hamburger">
      <div class="line1"></div>
      <div class="line2"></div>
      <div class="line3"></div>
    </div>

    <main>
      <!-- Sidebar -->
      <section id="sidebar">
        <div class="profile">
          <img src="{% static 'images/design.png' %}" alt="Profile picture" />
          <p class="mb-0 text text-center">Raynard Dodzi Helegah</p>
          <p class="m-0 text text-center text-muted">
            Software Engineer & Developer
          </p>
        </div>

        <div class="sidebar-item">
          <div class="m-0 d-flex justify-content-between">
            <p class="m-0">Residence:</p>
            <p class="m-0 text text-muted">Ghana</p>
          </div>
          <div class="m-0 d-flex justify-content-between">
            <p class="m-0">City:</p>
            <p class="m-0 text text-muted">Accra</p>
          </div>
          <div class="m-0 d-flex justify-content-between">
            <p class="m-0">Education:</p>
            <p class="m-0 text text-muted">University of Ghana</p>
          </div>
        </div>

        <div class="sidebar-item">
          <p class="m-0 text-primary">Languages</p>
          <div class="m-0 d-flex flex-wrap">
            <p class="m-0 mx-1 text text-muted">Python;</p>
            <p class="m-0 mx-1 text text-muted">Java;</p>
            <p class="m-0 mx-1 text text-muted">JavaScript;</p>
            <p class="m-0 mx-1 text text-muted">C/C++;</p>
            <p class="m-0 mx-1 text text-muted">Kotlin;</p>
            <p class="m-0 mx-1 text text-muted">Dart;</p>
            <p class="m-0 mx-1 text text-muted">HTML;</p>
            <p class="m-0 mx-1 text text-muted">CSS;</p>
          </div>
        </div>

        <div class="sidebar-item">
          <p class="m-0 text-primary">Frameworks</p>
          <div class="m-0 d-flex flex-wrap">
            <p class="m-0 mx-1 text text-muted">Django;</p>
            <p class="m-0 mx-1 text text-muted">Native Android;</p>
            <p class="m-0 mx-1 text text-muted">Flutter;</p>
            <p class="m-0 mx-1 text text-muted">React;</p>
            <p class="m-0 mx-1 text text-muted">Bootstrap;</p>
          </div>
        </div>

        <div class="sidebar-item">
          <p class="m-0 text-primary">Toolkits</p>
          <div class="m-0 d-flex flex-wrap">
            <p class="m-0 mx-1 text text-muted">Git (GitHub, GitBucktet);</p>
            <p class="m-0 mx-1 text text-muted">VS Code;</p>
            <p class="m-0 mx-1 text text-muted">Nginx;</p>
            <p class="m-0 mx-1 text text-muted">Vim;</p>
            <p class="m-0 mx-1 text text-muted">Gunicorn;</p>
            <p class="m-0 mx-1 text text-muted">Celery;</p>
            <p class="m-0 mx-1 text text-muted">Redis;</p>
            <p class="m-0 mx-1 text text-muted">Ubuntu;</p>
          </div>
        </div>

        <div class="sidebar-item">
          <p class="m-0 text-primary">Contact</p>
          <div class="m-0 d-flex justify-content-between">
            <p class="m-0">Email:</p>
            <p class="m-0 text text-muted">
              <a href="mailto:dodzireynard@gmail.com">dodzireynard@gmail.com</a>
            </p>
          </div>
          <div class="m-0 d-flex justify-content-between">
            <p class="m-0">Phone:</p>
            <p class="m-0 text text-muted">
              <a target="_blank" href="tel:+233249626071">+233 24 962 6071</a>
            </p>
          </div>
          <div class="m-0 d-flex justify-content-between">
            <p class="m-0">LinkedIn:</p>
            <p class="m-0 text text-muted">
              <a
                target="_blank"
                href="https://www.linkedin.com/in/raynard-dodzi-helegah-a46a17169/"
                >dodziraynard</a
              >
            </p>
          </div>
        </div>
      </section>

      <!-- Main page -->

      {% block content %} {% endblock %}
    </main>

    <script src="{% static 'js/website_app.js' %}"></script>
  </body>
</html>

website/templates/website/index.html
{% extends 'website/base_template.html' %} {% block content %}

<section id="main">
  <div class="p-5 intro">
    <h1 class="col-md-5">Discover my Amazing Portfolio!</h1>
    <p>
      &lt;<span class="text-primary">raynard</span>&gt; Built using Django
      &lt;/<span class="text-primary">raynard</span>&gt;
    </p>

    <a href="{% url 'website:projects' %}"
      ><button class="btn btn-warning">PROJECTS</button></a
    >
  </div>
  <div class="col-md-7 col-sm-12 mx-auto p-3 d-flex justify-content-between">
    <a href="{% url 'blog:index' %}" class="mx-1">
      <div class="d-flex">
        <p class="m-0 text text-primary mx-1">30+</p>
        <p class="m-0 text">Posts</p>
      </div>
    </a>

    <a href="https://github.com/dodziraynard/" class="mx-1">
      <div class="d-flex">
        <p class="m-0 text text-primary mx-1">30+</p>
        <p class="m-0 text">Repositories</p>
      </div>
    </a>

    <a href="https://play.google.com/store/apps/details?id=com.idea.mydiary" class="mx-1">
      <div class="d-flex">
        <p class="m-0 text text-primary mx-1">3</p>
        <p class="m-0 text">Apps in Store</p>
      </div>
    </a>
  </div>

  <div class="p-3 mx-4">
    <h4>Recent Posts</h4>

    <div class="row">
      {% for article in articles %}
      <div class="col-md-4 my-2">
        <a href="{% url 'blog:article' article.slug article.id %}">
          <div class="post-item">
            <p>{{article.title}}</p>
            <p class="text text-muted">{{article.summary}}</p>
            <a href="{% url 'blog:article' article.slug article.id %}" class="text-primary"
              >Read more >></a
            >
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>

  <hr />
  <!-- Footeer -->
  <footer class="p-3">
    <p class="text text-muted">
      &copy; 2021 Site by Raynard Dodzi.
    </p>
  </footer>
</section>

{% endblock %}

website/templates/website/projects.html
{% extends 'website/base_template.html' %} {% block content %}

<section id="main">
  <div class="p-5 intro">
    <h1 class="col-md-5">My Projects!</h1>
    <p>
      &lt;<span class="text-primary">languages</span>&gt; Python, JavaScript,
      Java, Kotlin &lt;/<span class="text-primary">languages</span>&gt;
    </p>

    <a href="{% url 'website:index' %}"
      ><button class="btn btn-warning">HOME</button></a
    >
  </div>

  <div class="p-3 mx-4">
    <h4>Project</h4>

    <div class="row">
      {% for project in projects %}
      <div class="col-md-4 my-2">
        <div class="post-item">
          <p>{{project.name}}</p>
          <p class="text text-muted">{{project.description|safe}}</p>
          {% if project.github_link %}
          <a href="{{project.github_link}}" class="text-primary">GitHub</a>
          {% endif %} {% if project.preview_link %}
          <a href="{{project.preview_link}}" class="text-primary"> | Preview</a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  <hr />
  <!-- Footeer -->
  <footer class="p-3">
    <p class="text text-muted">&copy; 2021 Site by Raynard Dodzi.</p>
  </footer>
</section>

{% endblock %}