amexpert/urls.py
from django.urls import path

from . import views

app_name = "amexpert"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("amexpert", views.IndexView.as_view(), name="amexpert"),
    path("next-event", views.NextEventView.as_view(), name="next_event"),
    path("new-membership",
         views.NewMemberShipView.as_view(),
         name="new_membership"),
    path("membership-created",
         views.MemberShipCreated.as_view(),
         name="membership_created"),
    path("events", views.EventsView.as_view(), name="events"),
    path("events/<str:event_id>/<str:slug>",
         views.EventDetailView.as_view(),
         name="event_detail"),
    path("post/<str:post_id>/<str:slug>",
         views.PostDetailView.as_view(),
         name="post_detail"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("store_article", views.store_article, name="store_article"),
    path("article/<str:slug>/<int:article_id>", views.article, name="article"),
    path("edit_article/<str:slug>/<int:article_id>", views.edit_article, name="edit_article"),
]

amexpert/models.py
from random import choice

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django_ckeditor_5.fields import CKEditor5Field


class Speaker(models.Model):
    fullname = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    photo = models.ImageField(upload_to="uploads")
    linkedin = models.URLField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    bio = CKEditor5Field()
    pronouns = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_created=True)
    update_at = models.DateTimeField(auto_now=True)
    visible = models.BooleanField(default=True)
    slug = models.CharField(max_length=250)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.fullname.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.fullname


class Sponser(models.Model):
    fullname = models.CharField(max_length=200)
    logo = models.ImageField(upload_to="uploads")
    about = CKEditor5Field()
    website = models.URLField()
    created_at = models.DateTimeField(auto_created=True)
    update_at = models.DateTimeField(auto_now=True)
    slug = models.CharField(max_length=250)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.fullname.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.fullname


class Event(models.Model):
    title = models.CharField(max_length=200)
    venue = models.CharField(max_length=200)
    details = CKEditor5Field()
    abstract = models.TextField()
    banner = models.ImageField(upload_to="uploads")
    small_banner = models.ImageField(upload_to="uploads",
                                     null=True,
                                     blank=True)
    timestamp = models.DateTimeField()
    sponsors = models.ManyToManyField(Sponser)
    speakers = models.ManyToManyField(Speaker)
    slug = models.CharField(max_length=250)
    registration_link = models.URLField(blank=True, null=True)
    visible = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_created=True)
    update_at = models.DateTimeField(auto_now=True)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.title.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    title = models.CharField('Title', max_length=200)
    image = models.ImageField(upload_to="uploads/images/articles")
    abstract = models.TextField()
    tags = models.CharField(max_length=300, default="")
    published = models.BooleanField(default=False)
    slug = models.CharField(max_length=300, unique=True)
    content = CKEditor5Field('Text', config_name='extends')
    created_at = models.DateTimeField(default=timezone.now)
    update_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,
                               null=True,
                               blank=True,
                               on_delete=models.CASCADE)

    def save(self) -> None:
        self.slug = "-".join(self.title.lower().split())
        return super().save()

    def __str__(self) -> str:
        return f"{self.id}. {self.title}"


class Member(models.Model):
    PRONOUNS = [('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'),
                ('Sir', 'Sir'), ('Madam', 'Madam')]
    fullname = models.CharField(max_length=200)
    email = models.EmailField(null=False, max_length=200)
    photo = models.ImageField(null=True,
                              upload_to='uploads/images/members',
                              blank=True)
    linkedin = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    contact = models.CharField(max_length=20, blank=True, null=True)
    bio = CKEditor5Field(blank=True)
    pronouns = models.CharField(max_length=100,
                                null=True,
                                blank=True,
                                choices=PRONOUNS)
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
    )
    update_at = models.DateTimeField(auto_now=True, null=False)
    visible = models.BooleanField(default=True)
    slug = models.CharField(max_length=250)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.fullname.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.fullname

amexpert/forms.py
from django import forms

from amexpert.models import Member


class NewMemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = [
            'fullname',
            'email',
            'photo',
            'linkedin',
            'contact',
            'github',
            'website',
            'bio',
            'pronouns',
        ]

amexpert/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import View

from amexpert.forms import NewMemberForm
from amexpert.models import Event, Post

from .utils import SendDynamic


class IndexView(View):
    template_name = "amexpert/website/index.html"

    def get(self, request):
        event = Event.objects.filter(
            timestamp__gte=timezone.now()).order_by("timestamp").first()
        posts = Post.objects.filter(published=True)
        context = {
            "event": event,
            "posts": posts,
        }
        return render(request, self.template_name, context)


class NextEventView(View):
    template_name = "amexpert/events/index.html"

    def get(self, request):
        event = Event.objects.filter(
            timestamp__gte=timezone.now()).order_by("timestamp").first()
        posts = Post.objects.filter(published=True)
        context = {
            "event": event,
            "posts": posts,
        }
        return render(request, self.template_name, context)


class EventsView(View):
    template_name = "amexpert/events/events.html"

    def get(self, request):
        events = Event.objects.filter(visible=True,
                                      timestamp__gte=timezone.now())
        context = {"events": events}
        return render(request, self.template_name, context)


class EventDetailView(View):
    template_name = "amexpert/events/event_detail.html"

    def get(self, request, event_id, **kwargs):
        event = get_object_or_404(Event, id=event_id)
        context = {"event": event}
        return render(request, self.template_name, context)


class PostDetailView(View):
    template_name = "amexpert/events/post_detail.html"

    def get(self, request, post_id, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        context = {"post": post}
        return render(request, self.template_name, context)


class MemberShipCreated(View):
    template_name = "amexpert/website/membership_created.html"

    def get(self, request):
        return render(request, self.template_name)


class NewMemberShipView(View):
    template_name = "amexpert/website/new_membership.html"

    def get(self, request):
        form = NewMemberForm()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = NewMemberForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # ...
            # redirect to a new URL:
            #    form.save()
            fullname = form.cleaned_data['fullname']
            #    subject= 'Thank you for your interest in joining AmExpert'
            #    message = 'Hi '+ fullname+ ',\nThank you for your interest in joining AmExpert. To complete the registration process, kindly follow these steps:\n\n1. Peruse our code of conduct at https://dodziraynard.me/pages/1/code-of-conduct\n2. Join our telegram page at https://t.me/+OvVzGg7OsQ83ZmVk\n\nIf you need any assistance, send your queries to dodzireynard@gmail.com or visit our page https://dodziraynard.me \n\nThanks you.\n\nAll the best,\nTeam AmExpert'
            #    email_from = settings.EMAIL_HOST_USER
            recipient_list = [form.cleaned_data['email']]
            SendDynamic('drhelegah@st.ug.edu.gh', recipient_list, fullname)
            #    send_mail( subject, message, email_from, recipient_list, fail_silently=False )

            return HttpResponseRedirect('/membership-created')
        return render(request, self.template_name, {'form': form})

amexpert/templates/amexpert/events/event_detail.html
{% extends 'amexpert/events/ase_template.html' %}
{% load static %}

{% block content %}



{% endblock %}

amexpert/templates/amexpert/events/index.html
{% extends 'amexpert/events/base_template.html' %}

{% if event.registration_link %}
{% block event_registration %}
<a class="lgx-btn lgx-btn-red" href="{{event.registration_link}}"><span>Register</span></a>
{% endblock %}
{% endif %}


{% load static %}

{% block content %}
<!--BANNER-->
<section>
    <div class="lgx-banner" id="lgx-banner" style="background-image: url('{{event.banner.url}}');">
        <div class="lgx-banner-style">
            <div class="lgx-inner lgx-inner-fixed">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="lgx-banner-info-area">
                                <div class="lgx-banner-info-circle">
                                    <div class="info-circle-inner" style="background-image: none;">
                                        <h3 class="date"><b class="lgx-counter">{{event.timestamp|date:"d"}}</b>
                                            <span>{{event.timestamp|date:"M"}}</span>
                                        </h3>
                                        <div class="lgx-countdown-area">
                                            <!-- Date Format :"Y/m/d" || For Example: 1017/10/5  -->
                                            <div id="lgx-countdown" data-date="{{event.timestamp|date:'Y/m/d'}}"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="lgx-banner-info">
                                    <!--lgx-banner-info-center lgx-banner-info-black lgx-banner-info-big lgx-banner-info-bg-->
                                    <!--banner-info-margin-->
                                    <h3 class="subtitle">Next Event</h3>
                                    <h2 class="title">{{event.title}}</h2>
                                    <h3 class="location"><i class="bi bi-geo-alt"></i> {{event.venue}}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--//.ROW-->
                </div>
                <!-- //.CONTAINER -->
            </div>
            <!-- //.INNER -->
        </div>
    </div>
</section>
<!--BANNER END-->


<!--ABOUT-->
<section>
    <div id="lgx-about" class="lgx-about">
        <div class="lgx-inner">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-7">
                        <div class="lgx-about-content-area">
                            <div class="lgx-heading">
                                <h2 class="heading">{{event.title}}</h2>
                                <h3 class="subheading">Do not miss this event, Why you should attend?</h3>
                            </div>
                            <div class="lgx-about-content">
                                <p class="text">{{event.abstract}}</p>
                                <div class="about-date-area">
                                    <h4 class="date"><span>{{event.timestamp|date:"d"}}</span></h4>
                                    <p><span>{{event.timestamp|date:"M Y"}}</span> {{event.venue}}</p>
                                </div>

                                <div class="section-btn-area">
                                    <a class="lgx-btn" href="/"><span>More About</span></a>
                                    {% if event.registration_link %}
                                    <a class="lgx-btn lgx-btn-red"
                                        href="{{event.registration_link}}"><span>Register</span></a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-5">
                        <div class="lgx-about-img-sp">
                            <img src="{{event.small_banner.url}}" alt="about">
                        </div>
                    </div>
                </div>
            </div><!-- //.CONTAINER -->
        </div><!-- //.INNER -->
    </div>
</section>
<!--ABOUT END-->


<!--SPEAKERS-->
<section>
    <div id="lgx-speakers" class="lgx-speakers lgx-speakers2">
        <div class="lgx-inner">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="lgx-heading lgx-heading-white">
                            <h2 class="heading">Who's Speaking</h2>
                            <h3 class="subheading">Welcome to our dedicated and remarkable Speakers!
                            </h3>
                        </div>
                    </div>
                </div>
                <!--//.ROW-->
                <div class="row">
                    {% for speaker in event.speakers.all %}
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="lgx-single-speaker">
                            <figure>
                                <a class="profile-img" href="{{speaker.website}}"><img src="{{speaker.photo.url}}"
                                        alt="speaker" /></a>
                                <figcaption>
                                    <div class="social-group">
                                        {% if speaker.website %}
                                        <a class="sp-fb" target="_blank" href="{{speaker.website}}"><i
                                                class="bi bi-globe"></i></a>
                                        {%endif%}
                                        {% if speaker.linkedin %}
                                        <a class="sp-in" target="_blank" href="{{speaker.linkedin}}"><i
                                                class="bi bi-linkedin"></i></a>
                                        {%endif%}
                                    </div>
                                    <div class="speaker-info">
                                        <h3 class="title"><a href="{{speaker.website}}">{{speaker.fullname}},
                                                {{speaker.pronouns}}</a></h3>
                                        <h4 class="subtitle">{{speaker.title}}</h4>
                                    </div>
                                </figcaption>
                            </figure>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!--//.ROW-->
                <div class="section-btn-area">
                    <a class="lgx-btn lgx-btn-red lgx-btn-big" href="mailto:drhelegah@st.ug.edu.gh"><span>Become A
                            Speaker</span></a>
                </div>
            </div>
            <!-- //.CONTAINER -->
        </div>
        <!-- //.INNER -->
    </div>
</section>
<!--SPEAKERS END-->

<!--SPONSORED-->
<section>
    <div id="lgx-sponsors" class="lgx-sponsors">
        <div class="lgx-inner-bg">
            <div class="lgx-inner">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="lgx-heading">
                                <h2 class="heading">Offcial Sponsonrs</h2>
                                <h3 class="subheading">Welcome to our remarkable Sponsores!</h3>
                            </div>
                        </div>
                    </div>
                    <!--//main row-->
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="sponsors-area sponsors-area-nogap sponsors-area-noshadow sponsors-area-col3">
                                {% for sponsor in event.sponsors.all %}
                                <div class="single">
                                    <a class="" href="{{sponsor.website}}"><img src="{{sponsor.logo.url}}"
                                            alt="sponsor" /></a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!--//col-->
                </div>
            </div>
            <!--//container-->
        </div>
    </div>
    <!--//lgx-inner-->
    </div>
</section>
<!--SPONSORED END-->

<!--News-->
<section>
    <div id="lgx-news" class="lgx-news">
        <div class="lgx-inner">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="lgx-heading">
                            <h2 class="heading">From Our Blog</h2>
                            <h3 class="subheading">Conferences dedicated to building remarkable events.</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for post in posts %}
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="lgx-single-news">
                            <figure>
                                <a href="{% url 'amexpert:post_detail'  post.id post.slug %}"><img
                                        src="{{post.image.url}}" alt="{{blog.title}}"></a>
                            </figure>
                            <div class="single-news-info">
                                <div class="meta-wrapper">
                                    <span>{{post.created_at|date}}</span>
                                    <span>by <a>{{post.author}}</a></span>
                                </div>
                                <h3 class="title"><a
                                        href="{% url 'amexpert:post_detail'  post.id post.slug %}">{{post.title}}</a>
                                </h3>
                                <a class="lgx-btn lgx-btn-white lgx-btn-sm" href="#"><span>Read More</span></a>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                </div>
                <div class="section-btn-area">
                    <a class="lgx-btn" href="">View More Blogs</a>
                </div>
            </div><!-- //.CONTAINER -->
        </div><!-- //.INNER -->
    </div>
</section>
<!--News END-->
{% endblock %}

amexpert/templates/amexpert/events/post_detail.html
{% extends 'amexpert/events/base_template.html' %}
{% block navclass %} menu-onscroll{%endblock%}
{% block pagetitle %}{{post.title}}{%endblock%}


{% block navmenus %}
<li><a href="/">Home</a></li>
{%endblock%}

{% block content %}
<section class="blog-section">
    {{post.content|safe}}
</section>
{% endblock %}