blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("store_article", views.store_article, name="store_article"),
    path("article/<str:slug>/<int:article_id>", views.article, name="article"),
    path("edit_article/<str:slug>/<int:article_id>", views.edit_article, name="edit_article"),
]

website/urls.py
from django.urls import path

from . import views

app_name = "website"

urlpatterns = [
    path("", views.index, name="index"),
    path("projects", views.projects, name="projects"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django_ckeditor_5.fields import CKEditor5Field


class Article(models.Model):
    title = models.CharField('Title', max_length=200)
    image = models.ImageField(upload_to="uploads/images/articles")
    summary = models.TextField()
    tags = models.CharField(max_length=300, default="")
    created_at = models.DateTimeField(default=timezone.now)
    published = models.BooleanField(default=False)
    slug = models.CharField(max_length=300, unique=True)
    text = CKEditor5Field('Text', config_name='extends')

    def save(self) -> None:
        self.slug = "-".join(self.title.lower().split())
        return super().save()

    def __str__(self) -> str:
        return f"{self.id}. {self.title}"

blog/forms.py
from django import forms

from .models import Article


class WalletForm(forms.ModelForm):
    description = forms.CharField(label='Description',
                   widget=forms.Textarea(attrs={'class': 'ckeditor'}))
    class Meta:
        model = Article
        fields = ["description"]

blog/views.py
from django.db.models import query
from django.db.models.query_utils import Q
from django.shortcuts import get_object_or_404, redirect, render

from .models import Article


def index(request):
    template_name = 'blog/index.html'

    query = request.GET.get("query", "")
    if query:
        articles = Article.objects.filter(
            Q(title__icontains=query) | Q(tags__icontains=query)
            | Q(text__icontains=query))
    else:
        articles = Article.objects.all()

    if not request.user.is_staff:
        articles = articles.filter(published=True)

    context = {
        "articles": articles.order_by("-created_at")[:20],
        "query": query,
    }
    return render(request, template_name, context)


def store_article(request):
    if request.method == "POST":
        text = request.POST.get("text")
        title = request.POST.get("title")
        published = 'on' in request.POST.get("published", "")

        id = request.POST.get("id")
        if id:
            Article.objects.filter(id=id).update(title=title,
                                                 text=text,
                                                 published=published)
        else:
            Article.objects.create(title=title, text=text, published=published)

        return redirect("blog:index")


def edit_article(request, slug, article_id):
    article = get_object_or_404(Article, id=article_id)

    template_name = 'blog/edit_article.html'
    context = {
        "article": article,
    }
    return render(request, template_name, context)


def article(request, slug, article_id):
    template_name = "blog/article.html"
    article = get_object_or_404(Article, id=article_id)
    articles = Article.objects.filter(tags__in=article.tags.split()).exclude(
        id=article.id)

    if not request.user.is_staff:
        articles = articles.filter(published=True)

    context = {
        "article": article,
        "articles": articles,
    }
    return render(request, template_name, context)

blog/templates/blog/article.html
{% extends 'blog/base_template.html' %} {% block content %}

<div class="col-md-8 col-11 mx-auto">
  <h2 class="mb-5">
    {% if request.user.is_staff %}
    <small
      ><a href="{% url 'blog:edit_article' article.slug article.id %}"
        >Edit</a
      ></small
    >
    {% endif %}
  </h2>

  <div>{{article.text|safe}}</div>
</div>

<br />
<br />

{% if articles %}
<div class="col-md-8 col-11 mx-auto">
  <h3>Related Posts</h3>
  <div class="row">
    <div class="col-md-4 my-2">
      {% for article in articles %}
      <a
        href="{% url 'blog:article' article.slug article.id %}"
        class="text-primary"
      >
        <div class="post-item">
          <h5>{{article.title}}</h5>
          <img
            src="/static/images/bg2.jpg"
            alt="post title"
            style="max-width: 100%"
          />
          <p class="text text-muted">{{article.summary}}</p>
          <a
            href="{% url 'blog:article' article.slug article.id %}"
            class="text-primary"
            >Read more >></a
          >
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</div>
{% else %}
<p class="text text info">No items found</p>
{% endif %} {% endblock %}

blog/templates/blog/base_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="theme-color" content="#1c1b24" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
    <title>Blog</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <link rel="stylesheet" href="{% static 'css/website_style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/blog_style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/blog_style_res.css' %}" />
  </head>

  <body>
    <nav class="mb-3">
      <form action="{% url 'blog:index' %}" method="get">
        <input
          type="search"
          name="query"
          id="query"
          value="{{query}}"
          placeholder="Search posts ..."
        />
        <button class="btn" type="submit">
          <svg
            fill="#eeeeee"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 50 50"
            width="30px"
            height="30px"
          >
            <path
              d="M 21 3 C 11.621094 3 4 10.621094 4 20 C 4 29.378906 11.621094 37 21 37 C 24.710938 37 28.140625 35.804688 30.9375 33.78125 L 44.09375 46.90625 L 46.90625 44.09375 L 33.90625 31.0625 C 36.460938 28.085938 38 24.222656 38 20 C 38 10.621094 30.378906 3 21 3 Z M 21 5 C 29.296875 5 36 11.703125 36 20 C 36 28.296875 29.296875 35 21 35 C 12.703125 35 6 28.296875 6 20 C 6 11.703125 12.703125 5 21 5 Z"
            />
          </svg>
        </button>
        &ThinSpace;
      </form>

      <ul>
        <li class="mx-3"><a href="{% url 'website:index' %}">Home</a></li>
        {% if request.user.is_authenticated %}
        <li class="mx-3"><a href="">Dashboard</a></li>
        {% endif %}
      </ul>
    </nav>

    {% block content %} {% endblock %} {% load static %}

    <hr />
    <footer class="p-3">
      <p class="text text-muted">
        &copy;2021 Designed and Coded by Raynard Dodzi.
      </p>
    </footer>

    <script src="{% static 'js/blog_app.js' %}"></script>
  </body>
</html>

blog/templates/blog/edit_article.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>

    <style>
      body {
        font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
      }
      input[name="title"] {
        padding: 1em 0em;
        font-size: 2em;
        outline: none;
        border: none;
        width: 100%;
      }

      .main {
        margin: 1% auto;
        width: 80%;
      }
    </style>

    {% load static %}
    <script src="{% static 'js/ckeditor.js' %}"></script>
  </head>

  <body>
    <section class="main">
      <form action="{% url 'blog:store_article' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{article.id}}" />

        <input
          type="text"
          name="title"
          id="title"
          required
          placeholder="Click to enter title"
          value="{{article.title}}"
        />

        <textarea class="ckeditor" name="text" id="editor" cols="30" rows="10">
{{article.text}}
</textarea
        >

        <br />
        <br />
        <br />

        <label for="published">Published</label>
        <input type="checkbox" name="published" id="published" {% if article.published %} checked {% endif %}>

        <button type="submit">Post</button>
      </form>

      <p><a href="{% url 'blog:index' %}">Posts</a></p>
    </section>

    <script>
      ClassicEditor.create(document.querySelector("#editor"), {
        codeBlock: {
          languages: [
            // Do not render the CSS class for the plain text code blocks.
            { language: "plaintext", label: "Plain text", class: "" },

            // Use the "php-code" class for PHP code blocks.
            { language: "php", label: "PHP", class: "php-code" },

            // Use the "js" class for JavaScript code blocks.
            // Note that only the first ("js") class will determine the language of the block when loading data.
            {
              language: "javascript",
              label: "JavaScript",
              class: "js javascript js-code",
            },

            // Python code blocks will have the default "language-python" CSS class.
            { language: "python", label: "Python" },
          ],
        },
        toolbar: {
          items: [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "|",
            "outdent",
            "indent",
            "|",
            "imageUpload",
            "blockQuote",
            "insertTable",
            "mediaEmbed",
            "undo",
            "redo",
            "codeBlock",
            "code",
            "CKFinder",
          ],
        },
        language: "en",
        licenseKey: "",
      })
        .then((editor) => {
          window.editor = editor;
        })
        .catch((error) => {
          console.error("Oops, something went wrong!");
          console.error(
            "Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:"
          );
          console.warn("Build id: s22u8iqzybqb-ijin7z70ew4f");
          console.error(error);
        });
    </script>
  </body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base_template.html' %} {% block content %}

<div class="col-md-8 col-11 mx-auto">
  <h3>Posts</h3>
  <div class="row">
    {% if articles %} 
    {% for article in articles %}
    <div class="col-md-4 my-2">
      <a href="{% url 'blog:article' article.slug article.id %}">
        <div class="post-item">
          <h5>{{article.title}}</h5>
          <img
            src="{{article.image.url}}"
            alt="{{article.title}}"
            style="max-width: 100%"
          />
          <p class="text text-muted">{{article.summary}}</p>

          <div class="d-flex justify-content-between">
            <p>
              <a
                href="{% url 'blog:article' article.slug article.id %}"
                class="text-primary"
                >Read more >></a
              >
            </p>

            {% if request.user.is_staff %}
            <p>
              <small
                ><a href="{% url 'blog:edit_article' article.slug article.id %}"
                  >Edit</a
                ></small
              >
            </p>
            {% endif %}
          </div>
        </div>
      </a>
    </div>
    {% endfor %} 
    {% else %}
    <p class="text text info">No items found</p>
    {% endif %}
  </div>
  {% endblock %}
</div>