amexpert/urls.py
from django.urls import path

from . import views

app_name = "amexpert"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("amexpert", views.IndexView.as_view(), name="amexpert"),
    path("next-event", views.NextEventView.as_view(), name="next_event"),
    path("new-membership",
         views.NewMemberShipView.as_view(),
         name="new_membership"),
    path("membership-created",
         views.MemberShipCreated.as_view(),
         name="membership_created"),
    path("events", views.EventsView.as_view(), name="events"),
    path("events/<str:event_id>/<str:slug>",
         views.EventDetailView.as_view(),
         name="event_detail"),
    path("post/<str:post_id>/<str:slug>",
         views.PostDetailView.as_view(),
         name="post_detail"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("store_article", views.store_article, name="store_article"),
    path("article/<str:slug>/<int:article_id>", views.article, name="article"),
    path("edit_article/<str:slug>/<int:article_id>", views.edit_article, name="edit_article"),
]

website/urls.py
from django.urls import path

from . import views

app_name = "website"

urlpatterns = [
    path("", views.index, name="index"),
    path("projects", views.projects, name="projects"),
]

amexpert/models.py
from random import choice

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django_ckeditor_5.fields import CKEditor5Field


class Speaker(models.Model):
    fullname = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    photo = models.ImageField(upload_to="uploads")
    linkedin = models.URLField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    bio = CKEditor5Field()
    pronouns = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_created=True)
    update_at = models.DateTimeField(auto_now=True)
    visible = models.BooleanField(default=True)
    slug = models.CharField(max_length=250)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.fullname.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.fullname


class Sponser(models.Model):
    fullname = models.CharField(max_length=200)
    logo = models.ImageField(upload_to="uploads")
    about = CKEditor5Field()
    website = models.URLField()
    created_at = models.DateTimeField(auto_created=True)
    update_at = models.DateTimeField(auto_now=True)
    slug = models.CharField(max_length=250)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.fullname.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.fullname


class Event(models.Model):
    title = models.CharField(max_length=200)
    venue = models.CharField(max_length=200)
    details = CKEditor5Field()
    abstract = models.TextField()
    banner = models.ImageField(upload_to="uploads")
    small_banner = models.ImageField(upload_to="uploads",
                                     null=True,
                                     blank=True)
    timestamp = models.DateTimeField()
    sponsors = models.ManyToManyField(Sponser)
    speakers = models.ManyToManyField(Speaker)
    slug = models.CharField(max_length=250)
    registration_link = models.URLField(blank=True, null=True)
    visible = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_created=True)
    update_at = models.DateTimeField(auto_now=True)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.title.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    title = models.CharField('Title', max_length=200)
    image = models.ImageField(upload_to="uploads/images/articles")
    abstract = models.TextField()
    tags = models.CharField(max_length=300, default="")
    published = models.BooleanField(default=False)
    slug = models.CharField(max_length=300, unique=True)
    content = CKEditor5Field('Text', config_name='extends')
    created_at = models.DateTimeField(default=timezone.now)
    update_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,
                               null=True,
                               blank=True,
                               on_delete=models.CASCADE)

    def save(self) -> None:
        self.slug = "-".join(self.title.lower().split())
        return super().save()

    def __str__(self) -> str:
        return f"{self.id}. {self.title}"


class Member(models.Model):
    PRONOUNS = [('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'),
                ('Sir', 'Sir'), ('Madam', 'Madam')]
    fullname = models.CharField(max_length=200)
    email = models.EmailField(null=False, max_length=200)
    photo = models.ImageField(null=True,
                              upload_to='uploads/images/members',
                              blank=True)
    linkedin = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    contact = models.CharField(max_length=20, blank=True, null=True)
    bio = CKEditor5Field(blank=True)
    pronouns = models.CharField(max_length=100,
                                null=True,
                                blank=True,
                                choices=PRONOUNS)
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
    )
    update_at = models.DateTimeField(auto_now=True, null=False)
    visible = models.BooleanField(default=True)
    slug = models.CharField(max_length=250)

    def save(self, **kwargs) -> None:
        self.slug = "-".join(self.fullname.lower().split())
        return super().save(**kwargs)

    def __str__(self) -> str:
        return self.fullname

website/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    github_link = models.URLField(null=True, blank=True)
    preview_link = models.URLField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name

class ProjectImage(models.Model):
    project = models.ForeignKey(Project,
                                related_name='images',
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to="uploads/images/articles")
    is_main = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.project.title

amexpert/forms.py
from django import forms

from amexpert.models import Member


class NewMemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = [
            'fullname',
            'email',
            'photo',
            'linkedin',
            'contact',
            'github',
            'website',
            'bio',
            'pronouns',
        ]

amexpert/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import View

from amexpert.forms import NewMemberForm
from amexpert.models import Event, Post

from .utils import SendDynamic


class IndexView(View):
    template_name = "amexpert/website/index.html"

    def get(self, request):
        event = Event.objects.filter(
            timestamp__gte=timezone.now()).order_by("timestamp").first()
        posts = Post.objects.filter(published=True)
        context = {
            "event": event,
            "posts": posts,
        }
        return render(request, self.template_name, context)


class NextEventView(View):
    template_name = "amexpert/events/index.html"

    def get(self, request):
        event = Event.objects.filter(
            timestamp__gte=timezone.now()).order_by("timestamp").first()
        posts = Post.objects.filter(published=True)
        context = {
            "event": event,
            "posts": posts,
        }
        return render(request, self.template_name, context)


class EventsView(View):
    template_name = "amexpert/events/events.html"

    def get(self, request):
        events = Event.objects.filter(visible=True,
                                      timestamp__gte=timezone.now())
        context = {"events": events}
        return render(request, self.template_name, context)


class EventDetailView(View):
    template_name = "amexpert/events/event_detail.html"

    def get(self, request, event_id, **kwargs):
        event = get_object_or_404(Event, id=event_id)
        context = {"event": event}
        return render(request, self.template_name, context)


class PostDetailView(View):
    template_name = "amexpert/events/post_detail.html"

    def get(self, request, post_id, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        context = {"post": post}
        return render(request, self.template_name, context)


class MemberShipCreated(View):
    template_name = "amexpert/website/membership_created.html"

    def get(self, request):
        return render(request, self.template_name)


class NewMemberShipView(View):
    template_name = "amexpert/website/new_membership.html"

    def get(self, request):
        form = NewMemberForm()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = NewMemberForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # ...
            # redirect to a new URL:
            #    form.save()
            fullname = form.cleaned_data['fullname']
            #    subject= 'Thank you for your interest in joining AmExpert'
            #    message = 'Hi '+ fullname+ ',\nThank you for your interest in joining AmExpert. To complete the registration process, kindly follow these steps:\n\n1. Peruse our code of conduct at https://dodziraynard.me/pages/1/code-of-conduct\n2. Join our telegram page at https://t.me/+OvVzGg7OsQ83ZmVk\n\nIf you need any assistance, send your queries to dodzireynard@gmail.com or visit our page https://dodziraynard.me \n\nThanks you.\n\nAll the best,\nTeam AmExpert'
            #    email_from = settings.EMAIL_HOST_USER
            recipient_list = [form.cleaned_data['email']]
            SendDynamic('drhelegah@st.ug.edu.gh', recipient_list, fullname)
            #    send_mail( subject, message, email_from, recipient_list, fail_silently=False )

            return HttpResponseRedirect('/membership-created')
        return render(request, self.template_name, {'form': form})

website/views.py
from django.shortcuts import render

from blog.models import Article

from .models import Project


def index(request):
    template_name = "website/index.html"
    articles = Article.objects.filter()
    if not request.user.is_staff:
        articles = articles.filter(published=True)

    context = {
        "articles": articles,
    }
    return render(request, template_name, context)


def projects(request):
    template_name = "website/projects.html"
    projects = Project.objects.filter()

    context = {
        "projects": projects,
    }
    return render(request, template_name, context)

amexpert/templates/amexpert/website/base_template.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>AmExpert</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/website/assets/img/logo.png" rel="icon">


  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/website/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="/static/website/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/website/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/website/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/website/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="/static/website/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/website/assets/css/style.css" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="/" class="logo d-flex align-items-center">
        <img src="/static/website/assets/img/logo.png" alt="">
        <span>AmExpert</span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto" href="#team">Team</a></li>
          <li><a class="getstarted scrollto" href="{% url 'amexpert:new_membership' %}">Join Us</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block content %}
  {% endblock content %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h4>Our Newsletter</h4>
            <p style="font-size: 15px;"> Please enter your e-mail and subscribe to receive our latest newsletter.</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
              {% csrf_token %}
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="/" class="logo d-flex align-items-center">
              <img src="/static/website/assets/img/logo.png" alt="">
              <span>AmExpert</span>
            </a>
            <p>The AmExpert program is here to help students learn valuable industry skills, secure opportunities
              and better prepare themselves to become the next generation of software developers.
            </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              <strong>University of Ghana, Department of Computer Science</strong> <br><br>
              <strong>Email:</strong> dodzireynard@gmail.com<br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">

        &copy;
        <script>document.write(new Date().getFullYear())</script> Copyright <strong><span>AmExpert</span></strong>. All
        Rights Reserved
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="/static/website/assets/vendor/purecounter/purecounter.js"></script>
  <script src="/static/website/assets/vendor/aos/aos.js"></script>
  <script src="/static/website/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/website/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/website/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/website/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/website/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/website/assets/js/main.js"></script>

</body>

</html>

amexpert/templates/amexpert/website/membership_created.html
{% extends 'amexpert/website/base_template.html' %}

{% block content %}
<main id="main">
  <section class="col-md-8 mx-auto">
    <h1 class="text text-center mt-5">Registration Complete, We'll Get back to you soon</h1>
  </section>
</main>

{% endblock content %}

amexpert/templates/amexpert/website/new_membership.html
{% extends 'amexpert/website/base_template.html' %}

{% block content %}
<main id="main">
  <section class="col-md-8 mx-auto justify-content-center">
    <h1 class="text text-center mt-2">New Registration</h1>
    {% load crispy_forms_tags %}
    <div class="container mt-5">
      <form action="/new-membership" method="POST" class="row justify-content-center" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="col-lg-8 form-group">
          <div class=" row">
            <div class="col-lg-3 form-group">
              {{ form.pronouns.errors }}
              {{ form.pronouns | as_crispy_field }}
            </div>
            <div class="col-lg-9 form-group">
              {{ form.fullname.errors }}
              {{ form.fullname | as_crispy_field }}
            </div>
          </div>

        </div>
        <div class="col-lg-8 form-group">
          <div class=" row">
            <div class="col-lg-4">
              {{ form.contact.errors }}
              {{ form.contact | as_crispy_field }}
            </div>
            <div class="col-lg-8">
              {{ form.email.errors }}
              {{ form.email | as_crispy_field }}

            </div>
          </div>

        </div>


        <div class="col-lg-8">
          {{ form.linkedin.errors }}
          {{ form.linkedin | as_crispy_field}}

        </div>
        <div class="col-lg-8">
          {{ form.github.errors }}
          {{ form.github | as_crispy_field}}

        </div>
        <div class="col-lg-8">
          {{ form.website.errors }}
          {{ form.website | as_crispy_field }}

        </div>
        <div class="col-lg-8">
          {{ form.photo.errors }}
          {{ form.photo | as_crispy_field }}

        </div>
        <div class="col-lg-8">
          {{ form.bio.errors }}
          {{ form.bio | as_crispy_field}}

        </div>
        <div class="col-lg-8">
          <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit" />
        </div>
      </form>
    </div>
  </section>
</main>

{% endblock content %}